services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:8000"
    environment:
      APP_URL: http://localhost:5555
      SESSION_DRIVER: file
      QUEUE_CONNECTION: sync
      CACHE_STORE: file
      OCTANE_SERVER: swoole
      OCTANE_HOST: 0.0.0.0
      OCTANE_PORT: 8000
    volumes:
      - ./storage:/var/www/html/storage
    restart: unless-stopped
